packageExtensions:
  koa-body@*:
    dependencies:
      "@types/koa": "*"
      koa: "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-berry.js
npmPublishAccess: "public"
